Data Encoding

1. Nominal /One Hot Encoder

In [3]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [4]:
##Create dataframe
df=pd.DataFrame({
    'color':['red','blue','green','red','blue']
})

In [5]:
df.head()

   color
0    red
1   blue
2  green
3    red
4   blue

In [6]:
##Create an instance
encoder=OneHotEncoder()

In [7]:
##perform fit and transform 
encoded=encoder.fit_transform(df[['color']]).toarray()

In [8]:
import pandas as pd
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [9]:
encoder_df.head()

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          0.0        1.0
4         1.0          0.0        0.0

In [10]:
encoder.transform([['blue']]).toarray()

/Users/adityasingh/ProjectsNew/MlPract/.venv/lib/python3.14/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [11]:
pd.concat([df,encoder_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3    red         0.0          0.0        1.0
4   blue         1.0          0.0        0.0

In [12]:
import seaborn as sns
sns.load_dataset('tips')

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [13]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()

In [14]:
lbl_encoder.fit_transform(df[['color']])

/Users/adityasingh/ProjectsNew/MlPract/.venv/lib/python3.14/site-packages/sklearn/preprocessing/_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 2, 0])

## Ordinal Encoding

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [17]:
df=pd.DataFrame({
    'size':['small','medium','large','medium','small','large']
})

In [18]:
df.head()

     size
0   small
1  medium
2   large
3  medium
4   small

In [20]:
##Create an instance of OrdinalEncoder and then fit_transform
encoder=OrdinalEncoder(categories=[['small','medium','large']])

In [21]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [22]:
encoder.transform([['small']])

/Users/adityasingh/ProjectsNew/MlPract/.venv/lib/python3.14/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])

In [25]:
import pandas as pd

df=pd.DataFrame({
    'city':['New York','London','Paris','Tokyo','New York','Paris'],
    'price':[200,150,300,250,180,320]
})

In [26]:
df

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180
5     Paris    320

In [29]:
mean_price=df.groupby('city')['price'].mean().to_dict()

In [30]:
mean_price

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [31]:
df['city_encoded']=df['city'].map(mean_price)

In [37]:
df[['price','city_encoded']]

   price  city_encoded
0    200         190.0
1    150         150.0
2    300         310.0
3    250         250.0
4    180         190.0
5    320         310.0

In [41]:
import seaborn as sns
df_w=sns.load_dataset('tips')
df_w.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [40]:
df_w['time'].unique()

['Dinner', 'Lunch']
Categories (2, str): ['Lunch', 'Dinner']

In [42]:
mean_pri=df_w.groupby('time')['total_bill'].mean().to_dict()

In [43]:
mean_pri

{'Lunch': 17.168676470588235, 'Dinner': 20.79715909090909}

In [44]:
df_w['time_encoded']=df_w['time'].map(mean_pri)

In [46]:
df_w[['total_bill','time_encoded','time']]

     total_bill time_encoded    time
0         16.99    20.797159  Dinner
1         10.34    20.797159  Dinner
2         21.01    20.797159  Dinner
3         23.68    20.797159  Dinner
4         24.59    20.797159  Dinner
..          ...          ...     ...
239       29.03    20.797159  Dinner
240       27.18    20.797159  Dinner
241       22.67    20.797159  Dinner
242       17.82    20.797159  Dinner
243       18.78    20.797159  Dinner

[244 rows x 3 columns]

In [47]:
df_w['time_encoded'].unique()

[20.797159, 17.168676]
Categories (2, float64): [17.168676, 20.797159]