Flight Price Prediction

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [11]:
df=pd.read_excel('flight_price.xlsx')

In [12]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [13]:
df.tail()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [14]:
##Basic info about data
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
dtypes: int64(1), str(10)
memory usage: 918.2 KB

In [15]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [19]:
## Feature Engineering
df['Date']=df['Date_of_Journey'].str.split('/').str[0]
df['Month']=df['Date_of_Journey'].str.split('/').str[1]
df['Year']=df['Date_of_Journey'].str.split('/').str[2]

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
 11  Data             10683 non-null  object
 12  Date             10683 non-null  object
 13  Month            10683 non-null  object
 14  Year             10683 non-null  object
dtypes: int64(1), object(4), str(10)
memory usage: 1.2+ MB

In [23]:
df['Date']=df['Date'].astype(int)
df['Month']=df['Month'].astype(int)
df['Year']=df['Year'].astype(int)

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
 11  Data             10683 non-null  object
 12  Date             10683 non-null  int64
 13  Month            10683 non-null  int64
 14  Year             10683 non-null  int64
dtypes: int64(4), object(1), str(10)
memory usage: 1.2+ MB

In [29]:
df.drop('Date_of_Journey',axis=1,inplace=True)
df.drop('Data',axis=1,inplace=True)

In [30]:
df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019

In [37]:
df['Arrival_Time']=df['Arrival_Time'].apply(lambda x:x.split(' ')[0])

In [58]:
df['Hours']=df['Arrival_Time'].str.split(':').str[0]
df['Minutes']=df['Arrival_Time'].str.split(':').str[1]

KeyError: 'Arrival_Time'

In [49]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Source           10683 non-null  str
 2   Destination      10683 non-null  str
 3   Route            10682 non-null  str
 4   Dep_Time         10683 non-null  str
 5   Duration         10683 non-null  str
 6   Total_Stops      10682 non-null  str
 7   Additional_Info  10683 non-null  str
 8   Price            10683 non-null  int64
 9   Date             10683 non-null  int64
 10  Month            10683 non-null  int64
 11  Year             10683 non-null  int64
 12  Hours            10683 non-null  int64
 13  Minutes          10683 non-null  int64
 14  Dep_Hours        10683 non-null  object
 15  Dep_Minutes      10683 non-null  object
 16  Arrival_Hours    10683 non-null  int64
 17  Arrival_Minutes  10683 non-null  int64
dtypes: int64(8), object(2), str(8)
memory usage: 1.5+ MB

In [46]:
df['Arrival_Hours']=df['Hours'].astype(int)
df['Arrival_Minutes']=df['Minutes'].astype(int)

In [56]:
df.drop('Arrival_Hours',axis=1,inplace=True)
df.drop('Arrival_Minutes',axis=1,inplace=True)

In [55]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Source           10683 non-null  str
 2   Destination      10683 non-null  str
 3   Route            10682 non-null  str
 4   Dep_Time         10683 non-null  str
 5   Duration         10683 non-null  str
 6   Total_Stops      10682 non-null  str
 7   Additional_Info  10683 non-null  str
 8   Price            10683 non-null  int64
 9   Date             10683 non-null  int64
 10  Month            10683 non-null  int64
 11  Year             10683 non-null  int64
 12  Hours            10683 non-null  int64
 13  Minutes          10683 non-null  int64
 14  Dep_Hours        10683 non-null  object
 15  Dep_Minutes      10683 non-null  object
 16  Arrival_Hours    10683 non-null  int64
 17  Arrival_Minutes  10683 non-null  int64
dtypes: int64(8), object(2), str(8)
memory usage: 1.5+ MB

In [45]:
df['Dep_Hours']=df['Dep_Time'].str.split(':').str[0]
df['Dep_Minutes']=df['Dep_Time'].str.split(':').str[1]

In [62]:
df['Dep_Hours']=df['Dep_Hours'].astype(int)
df['Dep_Minutes']=df['Dep_Minutes'].astype(int)

In [63]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Source           10683 non-null  str
 2   Destination      10683 non-null  str
 3   Route            10682 non-null  str
 4   Dep_Time         10683 non-null  str
 5   Duration         10683 non-null  str
 6   Total_Stops      10682 non-null  str
 7   Additional_Info  10683 non-null  str
 8   Price            10683 non-null  int64
 9   Date             10683 non-null  int64
 10  Month            10683 non-null  int64
 11  Year             10683 non-null  int64
 12  Hours            10683 non-null  int64
 13  Minutes          10683 non-null  int64
 14  Dep_Hours        10683 non-null  int64
 15  Dep_Minutes      10683 non-null  int64
dtypes: int64(8), str(8)
memory usage: 1.3 MB

In [64]:
df.head()

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Hours,Minutes,Dep_Hours,Dep_Minutes
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,2h 50m,non-stop,No info,3897,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,7h 25m,2 stops,No info,7662,1,5,2019,13,15,5,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,19h,2 stops,No info,13882,9,6,2019,4,25,9,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,5h 25m,1 stop,No info,6218,12,5,2019,23,30,18,5
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,4h 45m,1 stop,No info,13302,1,3,2019,21,35,16,50

In [65]:
df.drop('Dep_Time',axis=1,inplace=True)

In [66]:
df['Total_Stops'].unique()

<StringArray>
['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops']
Length: 6, dtype: str

In [70]:
df[df['Total_Stops'].isnull()]

Empty DataFrame
Columns: [Airline, Source, Destination, Route, Duration, Total_Stops, Additional_Info, Price, Date, Month, Year, Hours, Minutes, Dep_Hours, Dep_Minutes]
Index: []

In [69]:
df['Total_Stops']=df['Total_Stops'].map({'non-stop':0, '2 stops':2, '1 stop':1, '3 stops':3, '4 stops':4,np.nan:1})

In [86]:
df[df['Total_Stops'].isnull()]

Empty DataFrame
Columns: [Airline, Source, Destination, Duration, Total_Stops, Additional_Info, Price, Date, Month, Year, Hours, Minutes, Dep_Hours, Dep_Minutes, Duration_Hours, Duration_Mins]
Index: []

In [72]:
df.drop('Route',axis=1,inplace=True)

In [ ]:
df['Duration_Hours']=df['Duration'].str.split(' ').str[0].str.split('h').str[0]
df['Duration_Mins']=df['Duration'].str.split(' ').str[1].str.split('m').str[0]

In [89]:
df['Duration_Mins'] = df['Duration_Mins'].fillna(0).astype(int)

In [90]:
df[df['Duration_Mins'].isnull()]

Empty DataFrame
Columns: [Airline, Source, Destination, Duration, Total_Stops, Additional_Info, Price, Date, Month, Year, Hours, Minutes, Dep_Hours, Dep_Minutes, Duration_Hours, Duration_Mins]
Index: []

In [91]:
from sklearn.preprocessing import OneHotEncoder

In [92]:
encoder=OneHotEncoder()

In [94]:
encoder.fit_transform(df[['Airline','Source','Destination']]).toarray()

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.]], shape=(10683, 23))

In [95]:
pd.DataFrame(encoder.fit_transform(df[['Airline','Source','Destination']]).toarray(),columns=encoder.get_feature_names_out())

,Airline_Air Asia,Airline_Air India,Airline_GoAir,Airline_IndiGo,Airline_Jet Airways,Airline_Jet Airways Business,Airline_Multiple carriers,Airline_Multiple carriers Premium economy,Airline_SpiceJet,Airline_Trujet,...,Source_Chennai,Source_Delhi,Source_Kolkata,Source_Mumbai,Destination_Banglore,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
10679,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
10680,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
10681,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
10682,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [96]:
df.head()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Hours,Minutes,Dep_Hours,Dep_Minutes,Duration_Hours,Duration_Mins
0,IndiGo,Banglore,New Delhi,2h 50m,0,No info,3897,24,3,2019,1,10,22,20,2,0
1,Air India,Kolkata,Banglore,7h 25m,2,No info,7662,1,5,2019,13,15,5,50,7,0
2,Jet Airways,Delhi,Cochin,19h,2,No info,13882,9,6,2019,4,25,9,25,19,0
3,IndiGo,Kolkata,Banglore,5h 25m,1,No info,6218,12,5,2019,23,30,18,5,5,0
4,IndiGo,Banglore,New Delhi,4h 45m,1,No info,13302,1,3,2019,21,35,16,50,4,0